#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Gir bilder beskrivende navn og lager captions-fil per år."""
import os, json
from pathlib import Path

BASE = Path(__file__).parent / "bilder"

# Format: (old_name, new_name, caption)
RENAMES = {
    "2024": [
        ("raw-001.jpg", "drone-bat-siv-01.jpg",           "Fiskebåt langs sivkanten. Dronen følger spent med."),
        ("raw-002.jpg", "drone-borrevannet-gra-01.jpg",   "Borrevannet i grått morgenlys. Båten er en hvit prikk i nedre venstre hjørne."),
        ("raw-003.jpg", "drone-borrevannet-gra-02.jpg",   "Borrevannet fra oven – bred utsikt, overcast himmel."),
        ("raw-004.jpg", "drone-borrevannet-gra-03.jpg",   "Borrevannet i grå mai-stemning. Fiskerne er ute, optimismen er uknekket."),
        ("raw-005.jpg", "drone-bat-siv-02.jpg",           "Fiskebåt langs sivet. Andre runde."),
        ("raw-006.jpg", "drone-refleksjon-01.jpg",        "Borrevannet speil. Himmelen vet ikke om den er over eller under."),
        ("raw-007.jpg", "drone-refleksjon-02.jpg",        "Skyspeilsparade over Borrevannet. Fotografen er stille."),
        ("raw-008.jpg", "drone-refleksjon-03.jpg",        "Klassisk Borrevannet-refleksjon. Dette er festivalen på sitt vakreste."),
        ("raw-009.jpg", "drone-refleksjon-04.jpg",        "Borrevannet som lerret – skyer trykkes i vannet."),
        ("raw-010.jpg", "drone-refleksjon-fjord.jpg",     "Borrevannet med fjorden i horisonten. Dronen er fornøyd."),
        ("raw-011.jpg", "drone-refleksjon-fjord-02.jpg",  "Bred panorama mot fjorden. Borrevannet og himmel skilles knapt."),
        ("raw-012.jpg", "drone-bat-panorama.jpg",         "Fiskebåt liten i det store Borrevannet."),
        ("raw-013.jpg", "drone-borrevannet-gra-04.jpg",   "Borrevannet mot nordøst. Overcast, men stemningsfullt."),
        ("raw-014.jpg", "drone-borrevannet-gra-05.jpg",   "Mer Borrevannet. Dronen nekter å gå hjem."),
        ("raw-015.jpg", "drone-speiderhytta-luftfoto.jpg","Speiderhytta sett fra luften – golfbanen og Horten i bakgrunnen."),
        ("raw-016.jpg", "drone-horten-panorama-01.jpg",   "Horten og fjorden i dronehorisont. Borrevannet i forgrunnen."),
        ("raw-017.jpg", "drone-horten-panorama-02.jpg",   "Bred drone-panorama med Horten, fjord og skog."),
        ("raw-018.jpg", "drone-refleksjon-05.jpg",        "Borrevannet – båten er en prikk i det store speilet."),
        ("raw-019.jpg", "drone-refleksjon-06.jpg",        "Borrevannet refleksjon serie. Ingen to er like."),
        ("raw-020.jpg", "drone-refleksjon-07.jpg",        "Borrevannet panorama mot siv og åker."),
        ("raw-021.jpg", "drone-borrevannet-blatt-01.jpg", "Blått Borrevannet med fiskebåt i midten."),
        ("raw-022.jpg", "drone-borrevannet-blatt-02.jpg", "Borrevannet blåner til. Fiskerne er ute."),
        ("raw-023.jpg", "drone-borrevannet-blatt-03.jpg", "Borrevannet, blå himmel, to fiskere. Idyllisk."),
        ("raw-024.jpg", "drone-borrevannet-blatt-04.jpg", "Borrevannet fra dronen – bred og blå."),
        ("raw-025.jpg", "drone-bat-fiske-01.jpg",         "To fiskere med stenger ute, speilblankt Borrevannet."),
        ("raw-026.jpg", "drone-bat-fiske-02.jpg",         "Fiskebåt i midten av Borrevannet, refleksjon rundt."),
        ("raw-027.jpg", "drone-bat-fiske-03.jpg",         "Fiskebåt drone close-up serie. Stengene er ute."),
        ("raw-028.jpg", "drone-bat-fiske-04.jpg",         "To fiskere sett fra siden i fiskebåten."),
        ("raw-029.jpg", "drone-bat-fiske-05.jpg",         "Dronen holder øye med fiskeriene."),
        ("raw-030.jpg", "drone-speiderhytta-ovenfra.jpg", "Speiderhytta sett rett ovenfra. Det røde taket er lett å kjenne igjen."),
        ("raw-031.jpg", "drone-borrevannet-blatt-05.jpg", "Borrevannet i blåtimer. Fiskebåten er der fremdeles."),
        ("raw-032.jpg", "drone-borrevannet-blatt-06.jpg", "Borrevannet bred panorama mot nordvest."),
        ("raw-033.jpg", "drone-borrevannet-blatt-07.jpg", "Borrevannet – dronen tar en siste runde."),
        ("raw-034.jpg", "drone-borrevannet-blatt-08.jpg", "Borrevannet – avsluttende panoramashot."),
        ("raw-035.jpg", "gjedde-i-baten.jpg",             "To gjedder på båtbunnen med Skjærgårds Pils. Prioriteringene er klare."),
        ("raw-036.jpg", "gjedde-og-pils.jpg",             "Dagens fangst presenteres. Pilsen er der for kontekst."),
        ("raw-037.jpg", "fiske-bat-kveld-01.jpg",         "To gutter fisker fra gul båt i kveldssol."),
        ("raw-038.jpg", "fiske-bat-kveld-02.jpg",         "Kveldsfiske. Roen er total, humøret er høyt."),
        ("raw-039.jpg", "fiske-bat-kveld-03.jpg",         "Siste fiskeøkt. Dagslyset holder med nød og neppe."),
        ("raw-040.jpg", "kikker-og-stang.jpg",            "Kikkert i bruk, fiskestang ute. To fagpersoner i gul båt."),
        ("raw-041.jpg", "to-gutter-gul-bat.jpg",          "To gutter i gul båt, ansikt mot ansikt, begge med snurp. Gjedda er advart."),
        ("raw-042.jpg", "fiske-bat-sol-01.jpg",           "Solskinn over Borrevannet. Fiskebåten er i posisjon."),
        ("raw-043.jpg", "fiske-bat-sol-02.jpg",           "Blå himmel, blått vann, gul båt. Festivalen 2024 på sitt lyseste."),
        ("raw-044.jpg", "fiske-bat-sol-03.jpg",           "Sommerfiske i gul båt. Ingen gjedde har det trygt."),
        ("raw-045.jpg", "bat-selfie-roing.jpg",           "Roing i grønn genser, fisking bak. Festivalens arbeidsdeling er etablert."),
        ("raw-046.jpg", "roing-turkis-01.jpg",            "Turkiskledd roer i fokus. Solnedgangen samarbeider."),
        ("raw-047.jpg", "roing-turkis-02.jpg",            "Turkis overalt. Borrevannet er ikke overrasket."),
        ("raw-048.jpg", "fiske-bat-kveld-04.jpg",         "Kveldsfiske i gul båt. En fisker, en roer, en plan."),
        ("raw-049.jpg", "fiske-bat-kveld-05.jpg",         "Kveldsstemning på Borrevannet. Festivalens roligste time."),
        ("raw-050.jpg", "roing-solnedgang.jpg",           "Turkiskledd roer i kveldssol med hatten på. Et av årets beste portretter."),
        ("raw-051.jpg", "fiske-bat-morgen-01.jpg",        "Morgenfiske. Overcast, men klare for gjedde."),
        ("raw-052.jpg", "fiske-bat-morgen-02.jpg",        "Morgen nummer to. Optimismen er uendrelig."),
        ("raw-053.jpg", "fiske-bat-morgen-03.jpg",        "Fiskeøkt i grå morgen. Gjedda sover fremdeles."),
        ("raw-054.jpg", "fiske-bat-morgen-04.jpg",        "Fjerde morgenøkt. Stengene er ute, håpet likeså."),
        ("raw-055.jpg", "drone-bat-sol-01.jpg",           "Fiskebåten fra oven i solblink på vannet. Abstrakt og vakkert."),
        ("raw-056.jpg", "drone-bat-sol-02.jpg",           "Drone overhead, solrefleks på vannet. Båten er liten, vannet er stort."),
        ("raw-057.jpg", "drone-borrevannet-sol-01.jpg",   "Borrevannet i solskinn. Endelig."),
        ("raw-058.jpg", "drone-borrevannet-sol-02.jpg",   "Borrevannet solrefleksjon. Dronen er imponert over seg selv."),
        ("raw-059.jpg", "drone-borrevannet-sol-03.jpg",   "Sol og blå himmel over Borrevannet."),
        ("raw-060.jpg", "drone-horten-syd.jpg",           "Horten og Oslofjorden fra syd. Borrevannet i forgrunnen."),
        ("raw-061.jpg", "drone-borrevannet-sol-04.jpg",   "Borrevannet i sitt beste solskinn."),
        ("raw-062.jpg", "drone-borrevannet-sol-05.jpg",   "Bred panorama over Borrevannet, skyene har tatt fri."),
        ("raw-063.jpg", "drone-borrevannet-sol-06.jpg",   "Borrevannet fra oven, klart vær."),
        ("raw-064.jpg", "drone-borrevannet-sol-07.jpg",   "Avsluttende solparade over Borrevannet."),
        ("raw-065.jpg", "drone-skyskyggepanorama.jpg",    "Skyskyggene på vannet konkurrerer med båten om oppmerksomheten."),
        ("raw-066.jpg", "drone-borrevannet-sol-08.jpg",   "Borrevannet – sol og ro."),
        ("raw-067.jpg", "drone-bat-fiske-06.jpg",         "Fiskebåt sett fra siden i solskinn. Stengene ute."),
        ("raw-068.jpg", "drone-bat-fiske-07.jpg",         "Dronen har funnet sin favorittmotiv: to gutter i gul båt."),
        ("raw-069.jpg", "drone-bat-fiske-08.jpg",         "Drone fisker-dokumentasjon, dag to."),
        ("raw-070.jpg", "gul-bat-fiske-sol.jpg",          "To gutter fisker fra gul båt i stekende sol. En fisker, en administrerer."),
        ("raw-071.jpg", "drone-bat-fiske-09.jpg",         "Dronen nærmer seg fiskebåten igjen."),
        ("raw-072.jpg", "drone-bat-fiske-10.jpg",         "Samme båt, nesten samme vann, litt andre skyer."),
        ("raw-073.jpg", "drone-borrevannet-sol-09.jpg",   "Borrevannet bred panorama i solskinn."),
        ("raw-074.jpg", "drone-borrevannet-sol-10.jpg",   "Borrevannet fra oven – siste lystime."),
        ("raw-075.jpg", "drone-refleksjon-kveld.jpg",     "Borrevannet kveldspanorama med fiskebåt og perfekt skyrefleksjon."),
        ("raw-076.jpg", "drone-bat-kveld-01.jpg",         "Kveldsdrone – fiskebåten er fremdeles ute."),
        ("raw-077.jpg", "drone-bat-kveld-02.jpg",         "Kveldsstemning fra dronen. Siste runde."),
        ("raw-078.jpg", "drone-bat-kveld-03.jpg",         "Dronen og fiskerne avslutter dagen sammen."),
        ("raw-079.jpg", "drone-bat-kveld-04.jpg",         "Kveldsfiske fra luften. Ro og mørke nærmer seg."),
        ("raw-080.jpg", "mann-med-wobbler.jpg",           "Smilende mann viser frem grønn wobbler. Ikke gjedde, men vilje er det."),
        ("raw-081.jpg", "abbor-i-havet.jpg",              "Abbor i landingshøvet. Gul kniv parat. Saken er klar."),
        ("raw-082.jpg", "fiske-kveld-01.jpg",             "Fiskekveld på Borrevannet. Stemningen er høy."),
        ("raw-083.jpg", "fiske-kveld-02.jpg",             "Siste fisketur dag to. Optimistene er tilbake."),
        ("raw-084.jpg", "fiske-kveld-03.jpg",             "Fiskebåten ved solnedgang. Det er alltid tid for én cast til."),
        ("raw-085.jpg", "abbor-selfie.jpg",               "Mann poserer med abbor. Blikket sier: 'Dette er mine penger.'"),
        ("raw-086.jpg", "fangst-og-pils.jpg",             "Dagens resultat oppsummert: to gjedder og en øl. Festivalmålestokk."),
        ("raw-087.jpg", "roing-solnedgang-02.jpg",        "Turkiskledd roer med hatten på i kveldsgull. Festivalens mest ikoniske farge."),
        ("raw-088.jpg", "kveldsmat-ute.jpg",              "Tre gutter spiser ute ved det nye bordet. AXE 10% holder selskap."),
        ("raw-089.jpg", "kveldsmat-ute-02.jpg",           "Kveldsmåltid nummer to. Maten er god, stemningen bedre."),
        ("raw-090.jpg", "borrevannet-natt-01.jpg",        "Borrevannet i blåtimen. Brygga og båtene hviler etter lang dag."),
        ("raw-091.jpg", "borrevannet-natt-02.jpg",        "Nattlig Borrevannet fra land. Tausheten er festivalens stilleste øyeblikk."),
        ("raw-092.jpg", "bater-brygge-blatiime.jpg",      "Tre båter ved brygga i blåtimen. Det vakreste bildet fra 2024."),
    ],
    "2021": [
        ("raw-001.jpg", "pizza-og-ol.jpg",                   "Festivalmåltid. To skiver pizza og en Aas Vienna Lager. Festivalmenyen er satt."),
        ("raw-002.jpg", "gjedde-i-noten.jpg",                "Gjedde fanget i håven. Navnekonkurransen om festivalen er herved avgjort."),
        ("raw-003.jpg", "crush-i-baten.jpg",                 "Mango & Passionfruit Crush holdes frem som trofé. Roen bak er konsentrert om fisken."),
        ("raw-004.jpg", "kyss-til-gjedda-01.jpg",            "Kysser gjedda for kameraet. Gjedda er ikke begeistret, men stiller opp."),
        ("raw-005.jpg", "kyss-til-gjedda-02.jpg",            "Gjedda fra en annen vinkel. Stemningen er fremdeles ensidig."),
        ("raw-006.jpg", "stolt-gjeddefanger.jpg",            "Smilende gjeddefanger med årets beste fangst. Gjedda ser kritisk på saken."),
        ("raw-007.jpg", "bal-med-kniv-01.jpg",               "Kniven stikker opp fra balskålen som et skulpturelt statement. Ølen til høyre er enig."),
        ("raw-008.jpg", "bal-med-kniv-02.jpg",               "Flammene er høyere nå. Kniven er fast besluttet."),
        ("raw-009.jpg", "bal-natt-01.jpg",                   "Balskål natt – hvite flammer mot svart bakgrunn."),
        ("raw-010.jpg", "bal-natt-02.jpg",                   "To stokker, masse flammer. Ingen klager."),
        ("raw-011.jpg", "bal-natt-03.jpg",                   "Balskålen i nattmørket. Glasset til venstre venter tålmodig."),
        ("raw-012.jpg", "bal-blatimen.jpg",                  "Balskål i blåtimen. Flammene er oransje, himmelen er blå, livet er bra."),
        ("raw-013.jpg", "bal-natt-04.jpg",                   "Balskål sent på kveld. Festivalens eldste tradisjon."),
        ("raw-014.jpg", "bal-oransje.jpg",                   "Oransje flammer lyser opp kniven og antrekket hengt over kanten."),
        ("raw-015.jpg", "drone-fiskebat-01.jpg",             "To fiskere på Borrevannet, fanget av dronen. Gjedda er ikke varslet."),
        ("raw-016.jpg", "drone-fiskebat-02.jpg",             "Gul fiskebåt på mørkt vann – godt separert fra land og ansvar."),
        ("raw-017.jpg", "drone-borrevannet-panorama.jpg",    "Borrevannet i fugleflukt. Panorama mot sør."),
        ("raw-018.jpg", "drone-elvemunning.jpg",             "Elvemunningen der Borrevannet møter dyrket mark. Dronen er imponert."),
        ("raw-019.jpg", "drone-bare-vann-01.jpg",            "Bare vann. Dronen driftet litt for langt ut."),
        ("raw-020.jpg", "drone-bare-vann-02.jpg",            "Mer vann. Fremdeles ingen gjedde synlig fra luften."),
        ("raw-021.jpg", "drone-fiskebat-03.jpg",             "Den gule båten – liten, men stolt – midt på Borrevannet."),
        ("raw-022.jpg", "drone-fiskekonkurranse.jpg",        "Rød og gul båt på vannet. Kappestrid, men ingen vedder."),
        ("raw-023.jpg", "drone-fisking-ovenfra-01.jpg",      "To fiskere sett rett ovenfra, stenger ut i vannet."),
        ("raw-024.jpg", "drone-fisking-ovenfra-02.jpg",      "Samme båt, litt annen vinkel. Stengene peker jevnt ut."),
        ("raw-025.jpg", "drone-fisking-ovenfra-03.jpg",      "Gul båt fra oven. Begge fisker i full konsentrasjon."),
        ("raw-026.jpg", "drone-fisking-ovenfra-04.jpg",      "Dronen kretser. Fiskerne ignorerer den."),
        ("raw-027.jpg", "drone-fisking-skra-01.jpg",         "Gul båt fra skrå, stenger peiler ut."),
        ("raw-028.jpg", "drone-fisking-skra-02.jpg",         "Dronen sjekker inn på nytt. Fiskerne er fremdeles der."),
        ("raw-029.jpg", "drone-fisking-skra-03.jpg",         "Gul båt, to stenger, to håpefulle."),
        ("raw-030.jpg", "drone-fisking-skra-04.jpg",         "Fiskeoperasjonen dokumentert for siste gang. Foreløpig."),
        ("raw-031.jpg", "drone-speiderhytta-01.jpg",         "Speiderhytta fra oven – radardomen og brygga i front."),
        ("raw-032.jpg", "drone-speiderhytta-02.jpg",         "Borrevannet i grått kveldslys. Stille og vakkert."),
        ("raw-033.jpg", "drone-brygge-inn-01.jpg",           "Brygga med kajakker og robåter. Festivalens fiskefartøy ankommer."),
        ("raw-034.jpg", "drone-brygge-inn-02.jpg",           "Den gule båten returnerer. Ekspedisjonen er over."),
        ("raw-035.jpg", "drone-bat-alene.jpg",               "Gul båt alene på vannet. Speiderhytta og radardomen i bakgrunnen."),
        ("raw-036.jpg", "drone-bat-kvelds.jpg",              "Den gule båten på vei inn. Mot kvelden."),
        ("raw-037.jpg", "drone-bat-roing.jpg",               "Gul båt med to rykker på åren."),
        ("raw-038.jpg", "drone-bat-fiske-01.jpg",            "To fiskere sett fra siden i gul båt."),
        ("raw-039.jpg", "drone-bat-vinker.jpg",              "Fisker vinkler mot dronen. Dronen vinker ikke tilbake."),
        ("raw-040.jpg", "drone-bat-fiske-02.jpg",            "To fiskere på vei – fisketurens siste runde."),
        ("raw-041.jpg", "drone-bat-fiske-03.jpg",            "Fisker heiser armen mot dronen. Noen er bevisst på å bli dokumentert."),
        ("raw-042.jpg", "drone-bat-til-land.jpg",            "Den gule båten runder inn mot Speiderhytta. Radardomen er i sikte."),
        ("raw-043.jpg", "drone-speiderhytta-kveld-01.jpg",   "Speiderhytta fra oven i kveldslys, mot fjorden i bakgrunnen."),
        ("raw-044.jpg", "drone-speiderhytta-kveld-02.jpg",   "Speiderhytta med full oversikt – bygg, brygge, kajakker."),
        ("raw-045.jpg", "drone-borrevannet-kveld.jpg",       "Borrevannet i blåtime, mot fjorden i horisonten."),
        ("raw-046.jpg", "drone-speiderhytta-panorama.jpg",   "Speiderhytta fra oven – hele anlegget med skogen bak og fjorden foran."),
        ("raw-047.jpg", "drone-speiderhytta-side.jpg",       "Speiderhytta fra siden – trekanttak, kajakklager og radardomen."),
        ("raw-048.jpg", "drone-brygge-ovenfra.jpg",          "Brygga fra oven, den gule båten trygt fortøyd. Radardomen holder vakt."),
        ("raw-049.jpg", "drone-brygge-ankomst-01.jpg",       "To menn på brygga laster av utstyret. Fisketuren er over."),
        ("raw-050.jpg", "drone-brygge-ankomst-02.jpg",       "Brygga med gul fiskebåt og to menn på vei av."),
        ("raw-051.jpg", "brygge-lossing.jpg",                "Lossing fra den gule fiskebåten. Det viktige utstyret bæres nøye."),
        ("raw-052.jpg", "dronepiloter-ved-bord-01.jpg",      "To dronepiloter på benken utenfor Speiderhytta. Kontrollerne er klare."),
        ("raw-053.jpg", "dronepiloter-ved-bord-02.jpg",      "Dronepiloter i aksjon – eller pause. Vanskelig å si."),
        ("raw-054.jpg", "dronepiloter-selfie.jpg",           "De to dronepilotene tar selfie via dronen. Sjelden teknikk."),
        ("raw-055.jpg", "kart-horten.jpg",                   "Kart over Horten og Borrevannet på veggen. Festivalens navigasjonssentral."),
        ("raw-056.jpg", "agn-wobbler.jpg",                   "Oransje wobbler på rød stang. Gjedda visste ikke hva som traff den."),
        ("raw-057.jpg", "snelle-revo.jpg",                   "Abu Garcia Revo X-snellen i aksjon. Teknologien er imponerende. Resultatene varierer."),
        ("raw-058.jpg", "hengekove-speiderhytta.jpg",        "Hengekøye mellom trærne ved Speiderhytta. Tauene holder – til nå."),
    ],
    "2022": [
        ("raw-001.jpg", "grilling-i-regn.jpg",         "Festivalen 2022 – chef i regnjakke griller med urokkelig overbevisning. Solen valgte å ta fri."),
        ("raw-002.jpg", "kaffe-og-kamera.jpg",          "Ut på tur aldri sur – men videokameraet er på plass for å dokumentere hvert øyeblikk."),
        ("raw-003.jpg", "pizza-og-sertifikater.jpg",    "Pizzafredag innendørs. Sertifikatene på veggen bekrefter at dette er en sertifisert pizza-operasjon."),
    ],
    "2018": [
        ("raw-001.jpg", "robat-kveld-01.jpg",    "Ekspedisjon ut på Borrevannet. Navigasjon og åretak delegert til mannen foran."),
        ("raw-002.jpg", "robat-kveld-02.jpg",    "Kursendring under diskusjon. Begge parter er sterkt uenige om retningen."),
        ("raw-003.jpg", "robat-selfie.jpg",      "Selfie fra åren. Borrevannet nikker anerkjennende."),
        ("raw-004.jpg", "robat-kveld-04.jpg",    "Glad roer i rutete shorts. Meny-posen bakerst inngår i ballastsystemet."),
        ("raw-005.jpg", "polse-drop.jpg",        "Klassisk pølse-drop-teknikk. Innøvd over mange festivaler, utøvd med stolthet."),
        ("raw-006.jpg", "polseholdet.jpg",       "Pølsen fremvises for juryen. Nøyaktig karaktersetting pågår."),
    ],
    "2019": [
        ("raw-001.jpg", "utsikt-fra-terrassen.jpg",    "Utsikt fra Speiderhytta-terrassen. En øl i forgrunnen – alt er som det skal."),
        ("raw-002.jpg", "padling-i-sivet-01.jpg",      "Navigasjon gjennom sivskogen. Ekspedisjonsleder vet omtrent hvilken vei det er."),
        ("raw-003.jpg", "padling-i-sivet-02.jpg",      "Videre frem i sivet. Kartlegging av ukjente farvann pågår."),
        ("raw-004.jpg", "hengekove-solnedgang.jpg",    "Hengekøya i kveldslys. Solnedgangen er inkludert i prisen."),
        ("raw-005.jpg", "bal-ved-vannet-01.jpg",       "Bålkvelden starter. Brannvesenet er varslet – muntlig."),
        ("raw-006.jpg", "bal-ved-vannet-02.jpg",       "Bålet lever videre. Flammene er høyere enn protokollen antyder."),
        ("raw-007.jpg", "balvakt.jpg",                 "Bålvakt på post ved Borrevannet. Blikket sier: 'Ikke rør mitt bål.'"),
        ("raw-008.jpg", "bal-selskap.jpg",             "Bålkos med selskap. Hatten alene fortjener en bildetekst."),
        ("raw-009.jpg", "bal-sein-kveld.jpg",          "Kveldsbålet i sitt rette element. Ingen slukker dette frivillig."),
        ("raw-010.jpg", "hengekove-morgen.jpg",        "Morgenutsikt mot vannet. Hengekøyen er klar – innehaveren forhandler fortsatt."),
        ("raw-011.jpg", "hengekove-dag-01.jpg",        "Hengekøy dag to. Innehaveren har funnet sin livsvisjon."),
        ("raw-012.jpg", "hengekove-dag-02.jpg",        "Utsikten endrer seg ikke. Behovet for å flytte seg heller ikke."),
        ("raw-013.jpg", "hengekove-utsikt.jpg",        "Hengekøya med full fjordutsikt. Premium-plassering bekreftet."),
        ("raw-014.jpg", "utsikt-fra-hengekove.jpg",    "Morgenrapport innenfra hengekøyen: vann, trær, himmel. Alt er i orden."),
        ("raw-015.jpg", "trar-fra-bakken.jpg",         "Borrevannet sett nedenfra. Hengekøye-perspektivet er undervurdert."),
    ],
    "2026": [
        ("raw-001.jpg", "avgang-fra-brygga-2026.jpg",       "Klar for avgang – utstyret er stablet, håpet er hevet."),
        ("raw-002.jpg", "drone-borrevannet-kveld-01.jpg",   "Borrevannet i kveldsstemning – en ensom fisker i midten."),
        ("raw-003.jpg", "drone-borrevannet-kveld-02.jpg",   "Borrevannet, radardomen og kveldslyset. Klassisk Speiderhytta-utsikt."),
        ("raw-004.jpg", "drone-radardomen-ovenfra-01.jpg",  "Radardomen og brygga rett ovenfra. Alt er pent og ryddig."),
        ("raw-005.jpg", "drone-radardomen-ovenfra-02.jpg",  "Radardomen fra en annen vinkel. Like imponerende."),
        ("raw-006.jpg", "drone-hoyt-oslofjord-01.jpg",      "Høyt over Borrevannet – Oslofjorden og byer på begge sider."),
        ("raw-007.jpg", "drone-brygge-ovenfra.jpg",         "Brygga ovenfra – båtene parkert som en liten hvit flåte."),
        ("raw-008.jpg", "drone-skogskant-sjokant.jpg",      "Skog og vann møtes. Dronen filosoferer over overgangssoner."),
        ("raw-009.jpg", "drone-oslofjord-solnedgang.jpg",   "Oslofjorden i kveldsgull – Borrevannet i forgrunnen."),
        ("raw-010.jpg", "drone-menn-paa-terrassen.jpg",     "To menn fanget fra luften på Speiderhytta-terrassen. De aner ingenting."),
        ("raw-011.jpg", "drone-horten-panorama-01.jpg",     "Horten og Oslofjorden – full oversikt fra dronen."),
        ("raw-012.jpg", "drone-speiderhytta-side.jpg",      "Speiderhytta fra siden – gress, grus og gjedde-logistikk."),
        ("raw-013.jpg", "drone-horten-panorama-02.jpg",     "Horten by fra lufta – Borrevannet i forgrunnen."),
        ("raw-014.jpg", "drone-horten-panorama-03.jpg",     "Utsyn mot Oslofjorden. Festivalens utsiktspost."),
        ("raw-015.jpg", "lasting-ved-brygga.jpg",           "Tre menn laster to båter. Logistikkoperasjon i gang."),
        ("raw-016.jpg", "drone-horten-panorama-04.jpg",     "Enda et droneportrett av Horten og omegn."),
        ("raw-018.jpg", "speiderhytta-fasade.jpg",          "Speiderhytta i mai – hvit fasade, rødt tak, grønn stemning."),
        ("raw-021.jpg", "drone-speiderhytta-komplett.jpg",  "Hele Speiderhytta-anlegget fra oven – en festivalkommandoplass."),
        ("raw-022.jpg", "bat-forlater-brygga-kveld.jpg",    "Kveldsbåten forlater brygga. Radardomen vinker farvel."),
        ("raw-025.jpg", "drone-borrevannet-panorama-hoyt.jpg","Borrevannet i fugleperspektiv – skog og åker på alle sider."),
        ("raw-026.jpg", "drone-borrevannet-kveld-03.jpg",   "Kveldsdrone over Borrevannet. Den siste fisker er ute."),
        ("raw-027.jpg", "drone-radardomen-kveld.jpg",       "Radardomen og brygga i kveldslys."),
        ("raw-028.jpg", "drone-bat-minimal.jpg",            "Én båt, uendelig vann. Minimalistisk og vakkert."),
        ("raw-029.jpg", "bat-avgang-hund.jpg",              "Avgang med hund ombord – festivalens første og beste passasjer."),
        ("raw-031.jpg", "drone-bat-med-mannskap.jpg",       "Full mannsskapskapasitet fra luften. Åren er i posisjon."),
        ("raw-032.jpg", "rosa-gummisluk.jpg",               "Rosa gummisluk i vannet. Gjedda stirrer. Valget er vanskelig."),
        ("raw-033.jpg", "gjedde-fangst-01.jpg",             "Gjedde nummer én – mannen med de røde brillene er fornøyd."),
        ("raw-035.jpg", "ribeye-og-mais-paa-grill.jpg",     "To ribeye og to maiskolber. Festivalens høydepunkt er ikke fisken."),
        ("raw-037.jpg", "polse-og-ol-ute.jpg",              "Pølse med det hele og et glass craft-øl. Kveldsmaten er satt."),
        ("raw-038.jpg", "ribeye-med-bakt-potet.jpg",        "Ferdig grillet ribeye med to bakte poteter. Maillard approves."),
        ("raw-040.jpg", "gjedde-fangst-02.jpg",             "Gjedde nummer to – rett opp av vannet i strålende sol."),
        ("raw-041.jpg", "gjedde-fangst-03.jpg",             "Gjedda inspiseres på nært hold. Begge er fornøyd med møtet."),
        ("raw-042.jpg", "gjedde-fangst-04.jpg",             "Samme fangst, enda bredere smil. Borrevannet leverer."),
        ("raw-043.jpg", "gjedde-fangst-05.jpg",             "Stor gjedde med slukboks i bakgrunnen – alt på plass."),
        ("raw-044.jpg", "gjedde-fangst-06.jpg",             "Gjedda er nesten like lang som mannen er bred."),
        ("raw-046.jpg", "gjedde-fangst-07.jpg",             "Gjedda presenteres for ettertiden. Slukboksen er imponert."),
        ("raw-048.jpg", "gjedde-slipp-01.jpg",              "Gjedda holdes forsiktig før den slippes fri."),
        ("raw-049.jpg", "gjedde-slipp-02.jpg",              "Øyeblikket før gjedda returnerer til Borrevannet."),
    ],
    "2025": [
        ("raw-001.jpg", "drone-bat-mork-01.jpg",          "Dronen fant båten. Fisken fant skjulestedet sitt."),
        ("raw-002.jpg", "drone-borrevannet-panorama.jpg", "Borrevannet fra langt oppe – båten er en prikk, håpet er stort."),
        ("raw-003.jpg", "drone-hoyt-fjord.jpg",           "Høydrekord: Oslofjorden skimtes i horisonten bak Borrevannet."),
        ("raw-004.jpg", "drone-bat-ovenfra.jpg",          "Fugleperspektiv: båten ser liten ut. Fisken vet det."),
        ("raw-005.jpg", "drone-speiderhytta-brygge.jpg",  "Speiderhytta fra lufta – brygge, båter, klar for festival."),
        ("raw-006.jpg", "drone-speiderhytta-ovenfra.jpg", "Speiderhytta rett ovenfra. Det røde taket er lett å kjenne igjen."),
        ("raw-007.jpg", "drone-bat-ror-01.jpg",           "Dronen tett på – fiskerne aner ikke at de er fulgt."),
        ("raw-008.jpg", "drone-bat-ror-02.jpg",           "Roing i bølger dokumentert ovenfra. Dronen er tryggere ute."),
        ("raw-009.jpg", "drone-bat-siv-01.jpg",           "Langs sivet – der gjedda lurer og håpet blomstrer."),
        ("raw-010.jpg", "drone-bat-ror-03.jpg",           "Dronen nærmer seg. Fiskeplanene sjekkes ut."),
        ("raw-011.jpg", "drone-speiderhytta-panorama.jpg","Speiderhytta, brygga og Borrevannet – full festivalovervåkning."),
        ("raw-012.jpg", "drone-bat-siv-02.jpg",           "Tilbake til sivet. Den andre runden er alltid bedre."),
        ("raw-013.jpg", "speiderhytta-terrasse.jpg",      "Et sjeldent øyeblikk av sol på Speiderhytta-terrassen. Flagget er stolt."),
        ("raw-014.jpg", "roing-i-haglvaer.jpg",           "Hagl i ansiktet, åren i hånda. Borrevannet 2025 satte listen tidlig."),
        ("raw-015.jpg", "bat-selfie-regn.jpg",            "Selfie midt i snøbyge. Uvær er bare annen festival-stemning."),
        ("raw-016.jpg", "to-menn-i-regn.jpg",             "Rødbuks og grønnjakke – standhaftige sjeler begge to."),
        ("raw-017.jpg", "solbrille-selfie-vaat.jpg",      "Gjennomvåt solbrille-selfie. Brillene ser rolige ut, mannen bak likeså."),
        ("raw-018.jpg", "lasting-ved-brygga-01.jpg",      "Lasting av båten i tåke. Optimismen pakkes først."),
        ("raw-019.jpg", "lasting-ved-brygga-02.jpg",      "Utstyret inn, regnet ut. Avgang under åpent spørsmål."),
        ("raw-020.jpg", "presenning-i-vind.jpg",          "Presenning i vindkast er en teknikk for viderekomne."),
        ("raw-021.jpg", "roing-i-regn-01.jpg",            "Gjennomvåt og urokkelig – mannen nekter å la regnet vinne."),
        ("raw-022.jpg", "roing-i-regn-02.jpg",            "Portrett av en mann som har sett verre. Bergansen holder."),
        ("raw-023.jpg", "fiske-i-regn-01.jpg",            "Fiskestangen er ute, regnet er inn. Fisken bryr seg ikke om noen av delene."),
        ("raw-024.jpg", "fiske-i-regn-02.jpg",            "Ølen i båten overlever regnet. Det gjør håpet om gjedde også."),
        ("raw-025.jpg", "regnbue-med-stang-01.jpg",       "Regnbue over Borrevannet. Stangen pekte dit gullet burde ligge."),
        ("raw-026.jpg", "regnbue-vid-01.jpg",             "Full regnbue i vidvinkel. Naturen beklager forrige time."),
        ("raw-027.jpg", "regnbue-med-sluk.jpg",           "Dobbel gevinst: regnbue og sluk i ett bilde."),
        ("raw-028.jpg", "regnbue-med-ol.jpg",             "Regnbue + Frydenlund = Borrevannet-festivalen 2025 i ett bilde."),
        ("raw-029.jpg", "storm-og-sol-01.jpg",            "Stormen kommer bakfra – mannen smiler likevel."),
        ("raw-030.jpg", "storm-og-sol-02.jpg",            "Stående i båten under mørk himmel. En viking gjør det han må."),
        ("raw-031.jpg", "fiske-i-storm.jpg",              "Neongrønn sluk kastet mot mørk storm. Gjedda er enten imponert eller livredd."),
        ("raw-032.jpg", "sol-gjennom-storm.jpg",          "Solen brøt gjennom stormen i ett sekund. Det var nok til et bilde."),
        ("raw-033.jpg", "selfie-i-presenning.jpg",        "Presenning som regnhette – festivalens mest kreative løsning."),
        ("raw-034.jpg", "regnbue-touchdown.jpg",          "Regnbuen landet rett på Borrevannet. X markerer stedet der skatten ikke var."),
        ("raw-035.jpg", "regnbue-farger.jpg",             "Fargeeksplosjonen etter stormen – regnbuen på sitt beste."),
        ("raw-036.jpg", "kveldssol-roing-01.jpg",         "Kveldssol på speilblankt Borrevannet. Etter all regnet fortjente de dette."),
        ("raw-037.jpg", "kveldssol-roing-02.jpg",         "Skyene speiler seg i det stille vannet. Roingen er kontemplativ."),
        ("raw-038.jpg", "avgang-fra-brygga.jpg",          "Siste blikk mot brygga. Til neste år."),
        ("raw-039.jpg", "baring-av-utstyr.jpg",           "Fullt utstyrt på vei hjem. Fiskestengene stikker i alle retninger."),
        ("raw-040.jpg", "to-menn-ved-grill.jpg",          "To menn, ett flammende grill, ingen unnskyldninger."),
        ("raw-041.jpg", "cowboy-med-ol.jpg",              "Cowboys drikker Frydenlund – det er fastslått i felten."),
        ("raw-042.jpg", "cowboy-selfie.jpg",              "Cowboyen er klar. Er festivalen det?"),
        ("raw-043.jpg", "ved-til-grillen.jpg",            "Sjefsgrilleren tilfører ved – med ro og autoritet."),
        ("raw-044.jpg", "ved-grillen-01.jpg",             "Rødbuks er tilbake og grillklar."),
        ("raw-045.jpg", "ved-grillen-02.jpg",             "Ny pose, samme engasjement for ilden."),
        ("raw-046.jpg", "kjoett-paa-grill-01.jpg",        "Entrecoten møter flammen. Et historisk øyeblikk."),
        ("raw-047.jpg", "kjoett-paa-grill-02.jpg",        "Maillard-reaksjonen er i gang. Snart middag."),
    ],
    "2020": [
        ("raw-001.jpg", "drone-speiderhytta-01.jpg",    "Droneopptak over Speiderhytta. Det røde taket er vanskelig å gå glipp av."),
        ("raw-002.jpg", "drone-speiderhytta-02.jpg",    "Begge bygningene fra oven. Dronepiloten er fornøyd."),
        ("raw-003.jpg", "borrevannet-fra-drone-01.jpg", "Borrevannet i kveldslys. Sivet ser faktisk mye bedre ut herfra."),
        ("raw-004.jpg", "ankomst-speiderhytta.jpg",     "Ankomst 2020. Byggestillas i bakgrunnen er årets offisielle festivaldekor."),
        ("raw-005.jpg", "drone-solnedgang-fjord.jpg",   "Solnedgang over fjorden sett fra dronen. Kameraet er imponert."),
        ("raw-006.jpg", "ankomst-gjenger.jpg",          "Gjengen samler seg. Grilling-operasjonen er igangsatt med to griller."),
        ("raw-007.jpg", "drone-brygge-01.jpg",          "Brygga fra oven. To deltakere inspiserer noe som krever dyp konsentrasjon."),
        ("raw-008.jpg", "drone-speiderhytta-03.jpg",    "Speiderhytta fra oven i gul maiskog. Naturen er i festivalhumør."),
        ("raw-009.jpg", "grilling-oppstart.jpg",        "Tre gutter, to griller, én hemmelig plan."),
        ("raw-010.jpg", "drone-skog.jpg",               "Skogen rundt Borrevannet i kveldssol. Dronepiloten er i sitt element."),
        ("raw-011.jpg", "velkomst-ved-hytta.jpg",       "Gjengen ved hytta i kveldssol. Stillaset er årets signatur-bakgrunn."),
        ("raw-012.jpg", "drone-borrevannet-02.jpg",     "Borrevannet fra dronen med radardomen synlig. James Bond-vibes."),
        ("raw-013.jpg", "golden-hour-hytta.jpg",        "Kastanjetreet i golden hour. Festivalens beste fotospot."),
        ("raw-014.jpg", "grilling-oppstart-02.jpg",     "Grilling i gang, humøret er høyt, bålet er lavt."),
        ("raw-015.jpg", "drone-brygge-02.jpg",          "Brygga og kajakken fra oven. Alt er klart for ekspedisjon."),
        ("raw-016.jpg", "byggearbeid-kveld.jpg",        "Festival i forgrunnen, byggearbeid i bakgrunnen. Multitasking på høyt nivå."),
        ("raw-017.jpg", "drone-kastanjetre.jpg",        "Kastanjetreet sett rett ovenfra – en grønn kuppel i mai."),
        ("raw-018.jpg", "drone-borrevannet-03.jpg",     "Borrevannet i kveldssol med radardomen. Alltid malerisk."),
        ("raw-019.jpg", "drone-panorama.jpg",           "Panorama over Borrevannet mot fjorden. Dronen er fornøyd."),
        ("raw-020.jpg", "drone-solnedgang-02.jpg",      "Solnedgang over Borrevannet. Dronen henger i luften og nyter synet."),
        ("raw-021.jpg", "brygga-drone-launch.jpg",      "Droneoperasjonen koordineres fra brygga. Kameraet er allerede i gang."),
        ("raw-022.jpg", "drone-solnedgang-03.jpg",      "Siste solstråle over åsene. Dronen har fått det med seg."),
        ("raw-023.jpg", "middag-utenfor-01.jpg",        "Middag under kastanjetreet. Stillaset i bakgrunnen gir opp."),
        ("raw-024.jpg", "amerikansk-festivalfjes.jpg",  "Stars and Stripes-skjerf, Simms-caps og tommel opp. Festivalen er offisielt åpnet."),
        ("raw-025.jpg", "robat-selfie-2020.jpg",        "Robåt-selfie med Borrevannet i bakgrunnen. Stjerneskjerfet er tilbake."),
        ("raw-026.jpg", "robat-med-de-andre.jpg",       "De andre båtene i horisonten. Kappestrid pågår, men uoffisielt."),
        ("raw-027.jpg", "solnedgang-fra-brygga.jpg",    "Solnedgang fra brygga. Kraftlinjene er gratis inkludert."),
        ("raw-028.jpg", "middag-utenfor-02.jpg",        "Kveldsmåltid ute under treet. God stemning, god mat."),
        ("raw-029.jpg", "middag-utenfor-03.jpg",        "Middag ved solnedgang under kastanjetreet."),
        ("raw-030.jpg", "balplass-kveld.jpg",           "Bålplassen i kveldsstemning med utsikt over Borrevannet."),
        ("raw-031.jpg", "bal-gapahuken-01.jpg",         "Bål under gapahuken i blåtimen. Røde gnister mot blå himmel."),
        ("raw-032.jpg", "bal-gapahuken-02.jpg",         "Gnistfontene fra gapahuken. Sikkerhetsavstand er vurdert, ikke vedtatt."),
        ("raw-033.jpg", "bal-gapahuken-natt.jpg",       "Gapahuken sent på kveld. Stjerner og gnister – festivalkveldens beste bilde."),
        ("raw-034.jpg", "bal-gapahuken-folk.jpg",       "Gjengen rundt bålet i gapahuken. Ingen er trøtte."),
        ("raw-035.jpg", "hengekove-i-skog-01.jpg",      "Hengekøye i lauvskogen ved Borrevannet. Innehaveren er tilstede men usynlig."),
        ("raw-036.jpg", "hengekove-i-skog-02.jpg",      "Hengekøye dag to – med myggnettet på plass. Erfaringslæring."),
        ("raw-037.jpg", "robat-selfie-02.jpg",          "Robåt-selfie 2020, andre halvdel. Kappestriden er personlig."),
        ("raw-038.jpg", "solnedgang-fra-bat.jpg",       "Solnedgang sett fra robåten. Kraftlinjene er en del av kunstverket."),
        ("raw-039.jpg", "nattmørke.jpg",                "Nattbilde fra festivalen. Eksponeringstiden var litt optimistisk."),
        ("raw-040.jpg", "hengekove-skog-01.jpg",        "Hengekøye i grønn sommerskog. Perfekt gjemmested."),
        ("raw-041.jpg", "hengekove-skog-02.jpg",        "Hengekøye med myggnett – ikke til forhandling."),
        ("raw-042.jpg", "robat-selfie-03.jpg",          "Tredje robåt-selfie. Samme mann, samme vann, litt andre skyer."),
        ("raw-043.jpg", "solnedgang-over-vannet.jpg",   "Solnedgang over Borrevannet fra robåten. Ro og stillhet inkludert."),
        ("raw-044.jpg", "middag-ute-kveld.jpg",         "Kveldsmiddag under treet i siste dagslys."),
        ("raw-045.jpg", "bal-gapahuken-kveld.jpg",      "Gapahuken tidlig kveld – bålet tenner langsomt opp."),
        ("raw-046.jpg", "bal-gapahuken-gnister.jpg",    "Gapahuk-bålet i full blomst. Gnistene krever ekstra luftrom."),
    ],
}

captions_out = {}

for year, items in RENAMES.items():
    web_dir = BASE / year / "web"
    year_captions = {}
    for old, new, caption in items:
        src = web_dir / old
        dst = web_dir / new
        if src.exists() and not dst.exists():
            os.rename(src, dst)
            print(f"  {year}: {old} -> {new}")
        elif dst.exists():
            print(f"  {year}: {new} already exists, skipping rename")
        else:
            print(f"  {year}: MISSING {old}")
        year_captions[new] = caption
    captions_out[year] = year_captions

# Write captions JSON
captions_file = Path(__file__).parent / "captions.json"
existing = {}
if captions_file.exists():
    import json
    existing = json.loads(captions_file.read_text(encoding="utf-8"))
existing.update(captions_out)
import json
captions_file.write_text(json.dumps(existing, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"\nCaption-filen oppdatert: {captions_file}")
print("Ferdig.")
